### ISSUE TITLE
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by cmoulliard** [openshift/jenkins#369]
When a jenkins jnlp client running within a pod will access to a jenkins master server running outside of OpenShift, we get this error `javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed` when it tries to access the server

```
Warning: JnlpProtocol3 is disabled by default, use JNLP_PROTOCOL_OPTS to alter the behavior
Running java -Dorg.jenkinsci.remoting.engine.JnlpProtocol3.disabled=true -cp /usr/share/jenkins/slave.jar hudson.remoting.jnlp.Main -headless -url https://spring-boot-jenkins.rhev-ci-vms.eng.rdu2.redhat.com af2cfd3ffd09cfaa5e32092d645f045a9e553b1744de2b0be29130c07ad8a681 maven-1460a4dca61cd -credentials idm-jenkins:64b9d27465a93a511b9feea6b1862ecb
Aug 28, 2017 7:46:25 AM hudson.remoting.jnlp.Main createEngine
INFO: Setting up slave: maven-1460a4dca61cd
Aug 28, 2017 7:46:25 AM hudson.remoting.jnlp.Main$CuiListener <init>
INFO: Jenkins agent is running in headless mode.
Aug 28, 2017 7:46:25 AM hudson.remoting.Engine startEngine
WARNING: No Working Directory. Using the legacy JAR Cache location: ?/.jenkins/cache/jars
Aug 28, 2017 7:46:25 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Locating server among [https://spring-boot-jenkins.rhev-ci-vms.eng.rdu2.redhat.com]
Aug 28, 2017 7:46:25 AM hudson.remoting.jnlp.Main$CuiListener error
SEVERE: Failed to connect to https://spring-boot-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/tcpSlaveAgentListener/: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
java.io.IOException: Failed to connect to https://spring-boot-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/tcpSlaveAgentListener/: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver.resolve(JnlpAgentEndpointResolver.java:161)
	at hudson.remoting.Engine.innerRun(Engine.java:499)
	at hudson.remoting.Engine.run(Engine.java:451)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1959)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1514)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:961)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver.resolve(JnlpAgentEndpointResolver.java:158)
	... 2 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496)
	... 13 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
	... 19 more	
```

This issue is similar to this one : https://github.com/appscode-ci/cibox/issues/16

**Comment by bparees** [comment]
as with your other issue, you should be able to mount a proper truststore into the slave pod.

**Comment by gabemontero** [comment]
i think we can close this out ... if anybody disagrees, reopen and elaborate

thanks

**Comment by ManjushaQA** [comment]
When sending test mails in jenkins we are facing the same issue.sun.security.provider.certpath.SunCertPathBuilderException. Can any one help me out on this issue. 
![jenkinsissue](https://user-images.githubusercontent.com/32263961/33755696-134b28d2-dc18-11e7-847d-46f222f632ae.png)

**Comment by VEENAKVARMA** [comment]
i also got same error.can any body help me

**Comment by tomcooperca** [comment]
This solution I'm proposing may not help with malformed or self-signed certificates. 

If anyone is using their own CA and needs a custom truststore, the only sure-fire way I've found to do this on Jenkins & OpenShift is mounting a custom cacerts onto the system truststore. Copy a JDK system cacerts of choice, import your own CA certs, and mount it to the Jenkins pod via this deploymentconfig:

```yaml
apiVersion: v1
kind: DeploymentConfig
spec:
  template:
    spec:
      containers:
        - env:
          ...
          volumeMounts:
            - mountPath: /var/lib/jenkins
              name: jenkins-data
            - mountPath: /etc/pki/ca-trust/extracted/java
              name: jenkins-cert-bundle
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins-master
        - name: jenkins-cert-bundle
          secret:
            defaultMode: 420
            secretName: custom-cert-bundle
```

You might be able to do the same with importing self-signed certs into that truststore (although I wouldn't recommend it). 

The [standard instructions from Jenkins' documentation](https://support.cloudbees.com/hc/en-us/articles/203821254-How-to-install-a-new-SSL-certificate-) does not work in a non-privileged container as you cannot modify the system cacerts directly via standard RHEL means (such as `update-ca-trust`).

**Comment by VEENAKVARMA** [comment]
i have done it by disabling the certificate checking with reference to this site
https://stackoverflow.com/questions/19540289/how-to-fix-the-java-security-cert-certificateexception-no-subject-alternative

**Comment by xxdd10** [comment]
I downloaded certificate from brower https://plugins.jenkins.io/  
name as jenkins-plugin.cer.

 and use java cmd
> keytool -import -keystore "C:\Program Files\java\jdk1.8.0_31\jre\lib\security\cacerts"  -storepass changeit -keypass changeit -alias jenkinscert -file jenkins-plugin.cer

it doesn't work. --!

**Comment by bparees** [comment]
@xxdd10 you installed that cert on the jenkins slave image?

**Comment by prjvnd** [comment]
Are you making any HTTPS calls during the jenkin build process ?, you may consider to stop them

**Comment by rinormaloku** [comment]
> If anyone is using their own CA and needs a custom truststore, the only sure-fire way I've found to do this on Jenkins & OpenShift is mounting a custom cacerts onto the system truststore. Copy a JDK system cacerts of choice, import your own CA certs, and mount it to the Jenkins pod via this deploymentconfig:

The answer by @tomcooperca solved this issue for me. Though it was too short (for a java keystore beginner) and I had to do quite a lot of trial and error to find out. 

How keystore works is by importing CA certs and key certificate pairs into cacerts file. 
So instead of trying to create the cacerts file from you CA (root certificate) and or from your certificate key pairs, what you need to do is:

1. Install java on your system
2. find out the location of cacerts file (google about the defaults)
3. Open the **cacerts** file using the KeyStore explorer app.
4. With the file open click Tools > Import Trusted Certificate and import your root CA.
5. Repeat step 4 but now import the Key Pair.
6. Save this file somewhere.
7. Create secret from file and mount as explained by @tomcooperca 

fyi, this can be scripted using the keytool
