### ISSUE TITLE
can't build android projects due to ~/ being read only

### ISSUE THREAD

**Issue by spyhunter99** [openshift/jenkins#380]
Hi, I'm experimenting with openshift + jenkins + building a gradle/android project. I was able to get the gradlew wrapper to finally install itself by setting an environment variable in the job

And since i need jdk8 and yum isn't available via ssh, i was able to download the tar.gz and extract it to `app-root/dependencies/java` (not sure if this is the right thing to do or not)

finally, i ran into the following.
```
./sdkmanager update sdk -u -a -t platform-tool
Exception in thread "main" java.lang.RuntimeException: Cannot create directory /var/lib/openshift/myid/.android
        at com.android.utils.FileUtils.mkdirs(FileUtils.java:211)
        at com.android.prefs.AndroidLocation.getFolder(AndroidLocation.java:148)
        at com.android.sdklib.repository.AndroidSdkHandler.lambda$getInstance$12(AndroidSdkHandler.java:229)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
        at com.android.sdklib.repository.AndroidSdkHandler.getInstance(AndroidSdkHandler.java:224)
        at com.android.sdklib.tool.SdkManagerCli.main(SdkManagerCli.java:117)
        at com.android.sdklib.tool.SdkManagerCli.main(SdkManagerCli.java:93)
```

is there any way the .android folder can be created? I've tried to override this by exporting the HOME folder to be in `app-root` but unfortunately it doesn't work in this case and I'm not sure how to proceed

**Comment by bparees** [comment]
jdk8 should already be installed, not sure why you had to do anything for that:
https://github.com/openshift/jenkins/blob/master/2/Dockerfile#L36

Anyway if you do need additional tools in the jenkins image, the thing to do is to build your own image that extends our jenkins image:

FROM openshift/jenkins-2-centos7
USER root
RUN yum install whatever
USER 1001 # optional but a good practice

docker build .

then push that image up to a registry (the openshift registry or dockerhub) and use it.

Depending what openshift cluster you're using, you can even do the docker build of the extended image on the cluster itself.  (docker builds aren't permitted on the openshift online cluster, however).

Otherwise you are going to have permissions issues and you'll have to find a way to install your tools into /tmp or another path that your user has access to, which can be a struggle depending on what tools you're trying to use.
