### ISSUE TITLE
Request to have additional font packages installed

### ISSUE THREAD

**Issue by scoheb** [openshift/jenkins#399]
When using the very powerful Jenkins **monitoring** plugin, most graphs fail to render with this stack trace:

`java.lang.ArrayIndexOutOfBoundsException: 0
	at sun.font.CompositeFont.getSlotFont(CompositeFont.java:351)
	at sun.font.CompositeGlyphMapper.initMapper(CompositeGlyphMapper.java:81)
	at sun.font.CompositeGlyphMapper.<init>(CompositeGlyphMapper.java:62)
	at sun.font.CompositeFont.getMapper(CompositeFont.java:409)
	at sun.font.StandardGlyphVector.init(StandardGlyphVector.java:1122)
	at sun.font.StandardGlyphVector.<init>(StandardGlyphVector.java:172)
	at java.awt.Font.getStringBounds(Font.java:2421)
	at java.awt.Font.getStringBounds(Font.java:2331)
	at java.awt.Font.getStringBounds(Font.java:2365)
	at org.jrobin.graph.ImageWorker.getStringWidth(ImageWorker.java:166)
	at org.jrobin.graph.RrdGraph.getSmallFontCharWidth(RrdGraph.java:594)
	at org.jrobin.graph.RrdGraph.initializeLimits(RrdGraph.java:319)
	at org.jrobin.graph.RrdGraph.createGraph(RrdGraph.java:88)
	at org.jrobin.graph.RrdGraph.<init>(RrdGraph.java:59)`

I have traced it to the fact that there is only 1 font package installed on the master: **stix-fonts**

I found this BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1484079 that mentions that this cann happen when stix is the only font installed.

Would it be possible to install another one in the Dockerfile for CentOS?

I am no font expert...so not sure which one we can install to correct this problem.

Thanks

**Comment by bparees** [comment]
thanks, based on the bug you linked it looks like pretty much any font package will work.  I picked one and it seemed to make the graphs show up, so fixing it here:
https://github.com/openshift/jenkins/pull/400
