### ISSUE TITLE
NPE from openshift-login plugin in latest version (can't log in)

### ISSUE THREAD

**Issue by grdryn** [openshift/jenkins#743]
There was recently a bump of the openshift-login plugin here, from `1.0.9` to `1.0.10`. This seems to coincide with us no longer being able to login to our instance.

When I hit "Log In" in the top right of the Jenkins UI, which brings me to the blue "Log in with OpenShift" button page, I see the following in the Jenkins log:

```
Nov 14, 2018 1:19:07 PM io.fabric8.jenkins.openshiftsync.BuildWatcher reconcileRunsAndBuilds
INFO: Reconciling job runs and builds
Nov 14, 2018 1:19:12 PM org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm populateDefaults
INFO: OpenShift OAuth: provider: OpenShiftProviderInfo: issuer: <scrubbed> auth ep: <scrubbed>/oauth/authorize token ep: <scrubbed>/oauth/token
Nov 14, 2018 1:19:12 PM org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm populateDefaults
INFO: OpenShift OAuth returning true with namespace wendy SA dir null default /run/secrets/kubernetes.io/serviceaccount SA name null default jenkins client ID null default system:serviceaccount:wendy:jenkins secret null default <scrubbed>....... redirect null default https://ci.feedhenry.org:8443 server null default https://openshift.default.svc
```

Then when I hit the blue login button, I see this in the Jenkins log:

```
Nov 14, 2018 1:19:39 PM org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm populateDefaults
INFO: OpenShift OAuth: provider: OpenShiftProviderInfo: issuer: <scrubbed> auth ep: <scrubbed>/oauth/authorize token ep: <scrubbed>/oauth/token
Nov 14, 2018 1:19:39 PM org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm populateDefaults
INFO: OpenShift OAuth returning true with namespace wendy SA dir null default /run/secrets/kubernetes.io/serviceaccount SA name null default jenkins client ID null default system:serviceaccount:wendy:jenkins secret null default <scrubbed>....... redirect null default https://ci.feedhenry.org:8443 server null default https://openshift.default.svc
Nov 14, 2018 1:19:39 PM org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm getRoleToPermissionMap
INFO: OpenShift Jenkins Login Plugin could not find the openshift-jenkins-login-plugin-config config map in namespace wendy so the default permission mapping will be used
```

Then back in the UI, when I get redirected back to Jenkins after entering my OpenShift login details, I just get the following NPE trace, which doesn't show up in the Jenkins log (and I don't seem to get logged in to Jenkins):

<details>
java.lang.NullPointerException
	at org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm.postSAR(OpenShiftOAuth2SecurityRealm.java:606)
	at org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm.updateAuthorizationStrategy(OpenShiftOAuth2SecurityRealm.java:842)
	at org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm$7.onSuccess(OpenShiftOAuth2SecurityRealm.java:823)
	at org.openshift.jenkins.plugins.openshiftlogin.OAuthSession.doFinishLogin(OAuthSession.java:129)
	at org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm.doFinishLogin(OpenShiftOAuth2SecurityRealm.java:1067)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:117)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:129)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:734)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:864)
	at org.kohsuke.stapler.MetaClass$3.doDispatch(MetaClass.java:209)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:734)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:864)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:668)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at org.openshift.jenkins.plugins.openshiftlogin.OpenShiftPermissionFilter.doFilter(OpenShiftPermissionFilter.java:242)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at org.jenkinsci.plugins.ssegateway.Endpoint$SSEListenChannelFilter.doFilter(Endpoint.java:243)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at io.jenkins.blueocean.ResourceCacheControl.doFilter(ResourceCacheControl.java:134)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at io.jenkins.blueocean.auth.jwt.impl.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:61)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:211)
	at net.bull.javamelody.PluginMonitoringFilter.doFilter(PluginMonitoringFilter.java:88)
	at org.jvnet.hudson.plugins.monitoring.HudsonMonitoringFilter.doFilter(HudsonMonitoringFilter.java:114)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at jenkins.metrics.impl.MetricsFilter.doFilter(MetricsFilter.java:125)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:105)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
	at java.lang.Thread.run(Thread.java:748)
</details>

Is this a bug in the plugin, or do I need to change something to accomodate the new version? I haven't tried rolling back to an older version of our downstream image yet, since I've had unrelated issues with rolling back Jenkins before, and don't want to go through that again if at all possible! :)

Thanks for any help you can provide!

**Comment by gabemontero** [comment]
Hey @grdryn 

Makes no sense to me how you all are getting this :-(

Given [line 606](https://github.com/openshift/jenkins-openshift-login-plugin/blob/master/src/main/java/org/openshift/jenkins/plugins/openshiftlogin/OpenShiftOAuth2SecurityRealm.java#L606)

which is `for (String verb : roles)`

That would imply the instance variable `roles` is null.  However, that is [initialized on obj instantiation here](https://github.com/openshift/jenkins-openshift-login-plugin/blob/master/src/main/java/org/openshift/jenkins/plugins/openshiftlogin/OpenShiftOAuth2SecurityRealm.java#L151)

via `private ArrayList<String> roles = new ArrayList<String>(Arrays.asList( "admin", "edit", "view" ));`

and confirming the references, it is never replaced ... we just call clear or add on it if you have custom parameters.  However the presence of `could not find the openshift-jenkins-login-plugin-config config map in namespace` per the logs you noted indicate we don't even call clear or add on that array list.

Rather than you rolling back Jenkins, 
- could you provide the entire Jenkins pod log (I understand the exception is not in it) ... perhaps there are clues in some of the other messages
- you guys extend our image, right?  would it be easier for you to tolerate a custom built login plugin hpi file with debug and possible workarounds?

**Comment by grdryn** [comment]
> could you provide the entire Jenkins pod log (I understand the exception is not in it) ... perhaps there are clues in some of the other messages

Yes, sure, I'll send it to you privately if that's okay.

> you guys extend our image, right? would it be easier for you to tolerate a custom built login plugin hpi file with debug and possible workarounds?

Yeah we've got a custom downstream image based out of [this repo](https://github.com/feedhenry/wendy-jenkins-s2i-configuration/). I'm happy to try a custom build if you point me at one, but I might limit when I try it to when I know there won't be much activity there (even if people can't log in right now, they depend on it for status checks in pull requests). :+1:

**Comment by grdryn** [comment]
Thanks @gabemontero, that plugin change seemed to do the trick (the only thing was that I had to remember to change the .hpi extension to .jpi in my plugins/ directory to get it to work) :+1:

Not directly related question, but while we're talking about the login plugin: I seem to have to login quite regularly. I'm not sure what the timeout is. Is it configurable, e.g. could I set it to last longer?

**Comment by masodilosangeles** [comment]
FWIW, I believe we are experiencing this issue, as well.

Following the plugin update to v1.0.10 we were getting the same stacktrace that @grdryn posted above. Based on the updated README I created the following configMap, which got us a little bit further along. 

<details>
<summary>openshift-jenkins-login-plugin-config configMap</summary>

`apiVersion: v1
data:
  Agent-Build: admin,edit
  Agent-Configure: admin,edit
  Agent-Connect: admin,edit
  Agent-Create: admin,edit
  Agent-Delete: admin,edit
  Agent-Disconnect: admin,edit
  Credentials-Create: admin
  Credentials-Delete: admin
  Credentials-ManageDomains: admin
  Credentials-Update: admin
  Credentials-View: admin,edit
  Job-Build: admin,edit
  Job-Cancel: admin,edit
  Job-Configure: admin,edit
  Job-Create: admin,edit
  Job-Delete: admin,edit
  Job-Discover: admin,edit
  Job-Move: admin
  Job-Read: admin,edit
  Job-Workspace: admin,edit
  Overall-Administer: admin
  Overall-ConfigureUpdateCenter: admin
  Overall-Read: admin,edit
  Overall-RunScripts: admin,edit
  Overall-UploadPlugins: admin
  Run-Delete: admin
  Run-Replay: admin
  Run-Update: admin
  SCM-Tag: admin,edit
  View-Configure: admin
  View-Create: admin
  View-Delete: admin
  View-Read: admin
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: openshift-jenkins-login-plugin-config`

</details>

The head of our stacktrace now looks like this:
<details>
<summary>Stacktrace</summary>

`java.lang.NullPointerException
	at org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm.getRoleToPermissionMap(OpenShiftOAuth2SecurityRealm.java:751)
	at org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm.updateAuthorizationStrategy(OpenShiftOAuth2SecurityRealm.java:841)
	at org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm$7.onSuccess(OpenShiftOAuth2SecurityRealm.java:823)
	at org.openshift.jenkins.plugins.openshiftlogin.OAuthSession.doFinishLogin(OAuthSession.java:129)
	at org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm.doFinishLogin(OpenShiftOAuth2SecurityRealm.java:1067)`

</details>

[Line 751](https://github.com/openshift/jenkins-openshift-login-plugin/blob/master/src/main/java/org/openshift/jenkins/plugins/openshiftlogin/OpenShiftOAuth2SecurityRealm.java#L751) is the call to `roles.clear()`, which is what made me believe our problem is the same as this problem.

**Comment by gabemontero** [comment]
v1.0.11 of the login plugin has been initiated
